#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include <QValidator>

// Forward declaration of the UI class generated by Qt Designer
QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; }
QT_END_NAMESPACE

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    MainWindow(QWidget *parent = nullptr);
    ~MainWindow();

private slots:
    // Slots for Text Conversions Tab
    void on_btnTextToHex_clicked();
    void on_btnHexToText_clicked();
    void on_btnTextToBase64_clicked();
    void on_btnBase64ToText_clicked();
    void on_btnUrlEncode_clicked();
    void on_btnUrlDecode_clicked();

    // Slot for Hashing Tab
    void on_hashInputText_textChanged();

    // Slots for Number Base Conversions Tab
    void on_decLineEdit_textChanged(const QString &text);
    void on_hexLineEdit_textChanged(const QString &text);
    void on_binLineEdit_textChanged(const QString &text);
    void on_octLineEdit_textChanged(const QString &text);
    
    // Slots for Unix Timestamp Tab
    void on_btnTimestampToDate_clicked();
    void on_btnDateToTimestamp_clicked();
    void on_btnNow_clicked();

private:
    Ui::MainWindow *ui;

    // Helper functions to avoid infinite signal loops
    void updateNumberBases(qint64 value, QObject* sender);
    
    // Member variables to prevent recursive updates
    bool m_isUpdatingNumberBases = false;
    
    // Validators for number base inputs
    QValidator *decValidator;
    QValidator *hexValidator;
    QValidator *binValidator;
    QValidator *octValidator;
};

#endif // MAINWINDOW_H
